### ISSUE TITLE
[세션#4] 카카오 엔터프라이즈는 클라우드인가요 ?

### ISSUE THREAD

**Issue by archrua** [tangungithub/GDM2020-QnA#16]
### 세션#4 발표자
* 카카오 이호정 파트장: @benedict-lee

### 아래에 자유롭게 질문을 입력해주세요!

오늘 정말 감사했습니다 

깃허브를 도입하는 과정에 있는데요.

혹시, 카카오에서 사용하는 Github Enterpirse 는 클라우드 환경이 아니였던 건가요 ?

그렇다면 내년에는 클라우드 환경으로 이전하시는 건가요 ?

**Comment by benedict-lee** [comment]
@archrua 온프렘으로 사용중입니다. 
앞으로도 계속 온프렘을 유지하지 않을까 합니다.
