### ISSUE TITLE
[일반질문] Github Enterprise의 설치형과 Cloud 형의 차이에 대한 상세 매뉴얼이 있을까요?

### ISSUE THREAD

**Issue by byung-u** [tangungithub/GDM2020-QnA#7]
#### 상황
현재는 Github Enterprise 설치형(AWS용)을 사용하고 있습니다.

회사에서 핀테크 관련 서비스를 제공하기때문에 사업을 하려면 PCI-DSS를 비롯한 여러 인증이 필요합니다.
인증을 받는 조건중에 github에 로그인한(소스코드에 접근한) 사용자의 모든 행위는 로그에 남아야 합니다.
그래서 audit log 기능이 필요하다보니 올해부터 GHE 설치형을 사용하고 있습니다.

설치형으로 사용하고 있는데 GHE가 안정적으로 운용이 되다보니 최초 설치 이후에 작업할 일이 거의 없었습니다.
설치형과 Cloud형의 별다른 차이가 없다면
Cloud 형으로 옮기는것에 대해서 고민중에 있습니다.

#### 문의
GHE 설치형 -> Cloud형으로 옮기고 싶은데 둘간의 차이에 대해서 알 수 있는 상세 매뉴얼이 있을까요?
매뉴얼에서 알고 싶은 내용은
* audit log의 조회 및 보관
* redundancy
* 라이센스 갱신(만료로 인함, 사용자 증가로 인함, ...)
* cloud 형의 서버 상태 및 장애 알림 (콘솔로 제공되는 grafana 말고도 가능한 방법이 있는지)
* 등등...

**Comment by JamesJeongTangun** [comment]
안녕하세요, 단군소프트 정인수 입니다.

문의주신 내용 답변 드립니다.

* audit log의 조회 및 보관
조회는 가능하지만 로그 타입 별로 기간의 차이가 있으며, Cloud 의 경우 GitHub 본사의 데이터센터를 이용하므로 보관을 위해서는 Audit log API 를 이용하여 JSON 또는 CSV 형식으로 내보낼 수 있습니다.
만약 감사 등을 위해 로그 등이 필요하실 경우, 요청사유와 함께 GitHub 본사에 요청할 수 있습니다.

* redundancy
GitHub Enterprise Cloud 는 GitHub.com 에서 제공하는 SaaS 방식으로 모든 데이터는 GitHub 본사 정책에 따라 이중화 및 백업이 진행되고 있으므로 사용자가 별도로 이중화를 구성할 필요가 없습니다.

* 라이센스 갱신(만료로 인함, 사용자 증가로 인함, ...)
GitHub Enterprise 는 기본적으로 연단위의 라이선스로 On-premise 는 갱신 시점마다 신규 라이선스를 적용해주셔야 합니다.
Cloud 는 갱신이 완료되면 자동으로 사용기간이 늘어나므로 라이선스를 다시 적용하지 않아도 됩니다.
라이선스 사용 중 사용자 추가가 필요하실 경우, 만료기간까지의 일할계산된 금액으로 사용자 추가가 가능합니다.
이 때 Cloud 는 라이선스 적용 절차없이 사용자가 늘어나며, On-premise 는 신규 라이선스를 적용해주셔야 합니다.

* cloud 형의 서버 상태 및 장애 알림 (콘솔로 제공되는 grafana 말고도 가능한 방법이 있는지)
위에서도 말씀드렸듯이 Cloud 제품은 GitHub 본사의 데이터 센터를 이용하므로 서버 관리 또한 GitHub 본사에서 진행합니다.
GitHub Enterprise 는 SLA 를 보장하고 있으며, 문제가 발생할 경우 즉시 메일로 알람을 받으실 수 있습니다.

추가 문의사항이 있으실 경우, github@tangunsoft.com 으로 연락 주시기 바랍니다.

감사합니다.

**Comment by byung-u** [comment]
감사합니다~

**Comment by byung-u** [comment]
```
요청사유와 함께 GitHub 본사에 요청할 수 있습니다.
```

나머지는 다 만족스러운데
아무래도 이 부분이 좀 애매해서 GHE 설치형을 갱신해서 사용할 것 같습니다.
